name: qazquery
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.3.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  carousel_slider: ^5.0.0
  page_view_dot_indicator: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.7.2
  chewie: ^1.7.1
  win32: ^5.1.0
  get: ^4.6.6
  archive: ^4.0.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/json/
    - assets/videos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
